import { useState } from 'react'
import { createPortal } from 'react-dom'
import { X, Copy, Download, Sparkles, Check, RotateCcw } from 'lucide-react'

/* ─────────────────────────────────────────────────────────────
   MOOD DESIGNER, pick a mood, get a design-system .md file
   you can paste into Claude Code / Cursor / Codex.
   ───────────────────────────────────────────────────────────── */

const MOODS = {
  sad: {
    label: 'Sad',
    emoji: '🌧',
    accent: '#5B6BB8',
    blurb: 'Muted, slow, contemplative. Lots of breathing room.',
    palette: ['#0F1424', '#1E2440', '#5B6BB8', '#9AA3C7', '#E8EBF5'],
    typography: { display: 'Fraunces', body: 'Inter', mono: 'JetBrains Mono' },
    spacing: 'generous, 8 / 16 / 32 / 64 / 96',
    radii: 'soft, 4 / 8 / 16',
    shadows: 'soft, diffused, 0 12px 32px rgba(15,20,36,0.18)',
    voice: 'calm, measured, never shouts',
  },
  happy: {
    label: 'Happy',
    emoji: '☀️',
    accent: '#FF8A3D',
    blurb: 'Warm, rounded, optimistic. Tight rhythm, friendly type.',
    palette: ['#FF8A3D', '#FFD166', '#FFE9C9', '#2B2118', '#06D6A0'],
    typography: { display: 'Nunito', body: 'Nunito', mono: 'JetBrains Mono' },
    spacing: 'tight, 6 / 12 / 20 / 32 / 48',
    radii: 'pillowy, 12 / 20 / 999',
    shadows: 'playful, 0 8px 20px rgba(255,138,61,0.28)',
    voice: 'warm, conversational, light on jargon',
  },
  fun: {
    label: 'Fun',
    emoji: '🎉',
    accent: '#FF2E93',
    blurb: 'Electric, irreverent, loud. Hard shadows and chunky type.',
    palette: ['#FF2E93', '#C6FF00', '#00E5FF', '#0A0A0A', '#FFFFFF'],
    typography: { display: 'Space Grotesk', body: 'Inter', mono: 'JetBrains Mono' },
    spacing: 'punchy, 8 / 16 / 24 / 40 / 64',
    radii: 'chunky, 0 / 4 / 24',
    shadows: 'hard offset, 6px 6px 0 #0A0A0A',
    voice: 'playful, sharp, allergic to corporate-speak',
  },
}

function generateMd(moodKey, mood) {
  const [bg, surface, accent, muted, ink] = mood.palette
  return `# Design System, ${mood.label} mood

> ${mood.blurb}

## Palette

| Role     | Hex       |
|----------|-----------|
| Background | \`${bg}\` |
| Surface    | \`${surface}\` |
| Accent     | \`${accent}\` |
| Muted      | \`${muted}\` |
| Ink        | \`${ink}\` |

## Typography

- **Display:** ${mood.typography.display}
- **Body:** ${mood.typography.body}
- **Mono:** ${mood.typography.mono}

## Spacing

${mood.spacing}

## Radii

${mood.radii}

## Shadows

${mood.shadows}

## Voice

${mood.voice}

## Usage notes

- Treat **Accent** as the single hero color. Resist adding more.
- **Ink** is for primary text; **Muted** for secondary; never put Ink on Background without a Surface card between them.
- Pair display type sparingly, one headline per viewport.
- This file was generated by the *${mood.label}* mood (\`${moodKey}\`). Paste it into Claude Code, Cursor, or Codex as the design-system context for a new project.
`
}

/* ─────────────────────────────────────────────────────────────
   TILE, sits in the home canvas. Mirrors the photobooth /
   darkroom tile silhouette but with a gradient + sparkle vibe.
   ───────────────────────────────────────────────────────────── */
export function MoodDesignerTile({ height = 320 }) {
  const [hover, setHover] = useState(false)
  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        position: 'relative',
        width: '100%', height,
        background: 'linear-gradient(160deg,#FF2E93 0%,#FF8A3D 45%,#FFD166 100%)',
        border: '8px solid #2A1422',
        borderRadius: 14,
        boxShadow: hover
          ? '0 28px 50px rgba(255,46,147,0.45)'
          : '0 22px 42px rgba(0,0,0,0.4)',
        overflow: 'hidden',
        transform: hover ? 'translateY(-3px)' : 'translateY(0)',
        transition: 'transform 0.25s var(--ease), box-shadow 0.25s var(--ease)',
      }}
    >
      {/* Sign */}
      <div style={{
        position: 'absolute', top: 14, left: '50%', transform: 'translateX(-50%)',
        zIndex: 5, padding: '4px 10px',
        background: '#0A0A0A', color: '#fff',
        fontFamily: 'var(--font-mono)', fontSize: '0.58rem', fontWeight: 700,
        letterSpacing: '0.16em',
        boxShadow: '0 0 14px rgba(255,46,147,0.55)',
        borderRadius: 2,
      }}>
        MOOD DESIGNER
      </div>

      {/* Animated sparkles */}
      <div style={{
        position: 'absolute', inset: 50,
        background: 'radial-gradient(circle at 30% 30%, rgba(255,255,255,0.35) 0%, transparent 30%), radial-gradient(circle at 70% 70%, rgba(255,255,255,0.25) 0%, transparent 30%)',
        borderRadius: 6,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
        gap: 10, padding: '1rem',
        color: '#fff', textShadow: '0 2px 8px rgba(0,0,0,0.35)',
      }}>
        <Sparkles size={32} strokeWidth={2} style={{
          animation: 'hint-pulse 2.2s ease-in-out infinite',
          filter: 'drop-shadow(0 0 8px rgba(255,255,255,0.7))',
        }} />
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: '0.56rem',
          letterSpacing: '0.16em', textTransform: 'uppercase',
          opacity: 0.92,
        }}>
          what's your
        </span>
        <span style={{
          fontFamily: 'var(--font-display)', fontSize: '1.5rem', fontWeight: 800,
          letterSpacing: '-0.02em', lineHeight: 1,
        }}>
          mood today?
        </span>
        <span style={{
          marginTop: 8,
          fontFamily: 'var(--font-mono)', fontSize: '0.52rem',
          letterSpacing: '0.18em', textTransform: 'uppercase',
          opacity: 0.85,
        }}>
          click to begin
        </span>
      </div>
    </div>
  )
}

/* ─────────────────────────────────────────────────────────────
   MODAL
   ───────────────────────────────────────────────────────────── */
export function MoodDesignerModal({ onClose }) {
  const [moodKey, setMoodKey] = useState(null)
  const [palette, setPalette] = useState(null)
  const [copied, setCopied] = useState(false)

  const pickMood = (key) => {
    setMoodKey(key)
    setPalette([...MOODS[key].palette])
  }

  const mood = moodKey ? { ...MOODS[moodKey], palette } : null
  const md = mood ? generateMd(moodKey, mood) : ''

  const copyMd = async () => {
    try {
      await navigator.clipboard.writeText(md)
      setCopied(true)
      setTimeout(() => setCopied(false), 1600)
    } catch { /* */ }
  }
  const downloadMd = () => {
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `design-system-${moodKey}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
  const resetPalette = () => setPalette([...MOODS[moodKey].palette])

  return createPortal(
    <div
      onPointerDown={(e) => e.stopPropagation()}
      style={{
        position: 'fixed', inset: 0, zIndex: 99995,
        background: 'radial-gradient(ellipse at 50% 35%, #1a1027 0%, #050008 80%)',
        animation: 'fade-in 0.3s ease both',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 24,
      }}
    >
      {/* Close */}
      <button
        onClick={onClose}
        aria-label="Close mood designer"
        style={{
          position: 'fixed', top: 18, right: 22, zIndex: 100000,
          display: 'flex', alignItems: 'center', gap: 6,
          padding: '0.55rem 0.9rem', cursor: 'none',
          background: 'rgba(0,0,0,0.45)', border: '1px solid rgba(255,255,255,0.18)',
          borderRadius: 999, color: '#fff',
          fontFamily: 'var(--font-mono)', fontSize: '0.66rem',
        }}
      >
        <X size={13} /> close
      </button>

      {!moodKey && (
        <MoodPicker onPick={pickMood} />
      )}

      {moodKey && (
        <MoodResult
          moodKey={moodKey}
          mood={mood}
          md={md}
          palette={palette}
          onColorChange={(i, v) => setPalette(p => { const n = [...p]; n[i] = v; return n })}
          onReset={resetPalette}
          onBack={() => { setMoodKey(null); setPalette(null) }}
          onCopy={copyMd}
          copied={copied}
          onDownload={downloadMd}
        />
      )}
    </div>,
    document.body
  )
}

function MoodPicker({ onPick }) {
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 32,
      animation: 'fade-in 0.4s var(--ease) both',
    }}>
      <div style={{ textAlign: 'center' }}>
        <p style={{
          fontFamily: 'var(--font-mono)', fontSize: '0.62rem',
          color: '#FF8A3D', letterSpacing: '0.18em', textTransform: 'uppercase',
          marginBottom: 10,
        }}>
          # mood designer
        </p>
        <h2 style={{
          fontFamily: 'var(--font-display)', fontWeight: 800,
          fontSize: 'clamp(2rem, 5vw, 3.6rem)', color: '#fff',
          letterSpacing: '-0.03em', lineHeight: 1.05,
        }}>
          What’s your mood today?
        </h2>
        <p style={{
          fontFamily: 'var(--font-mono)', fontSize: '0.7rem',
          color: 'rgba(255,255,255,0.6)', marginTop: 12,
        }}>
          pick one, i’ll spit out a design-system .md you can paste into claude code, cursor or codex
        </p>
      </div>

      <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap', justifyContent: 'center' }}>
        {Object.entries(MOODS).map(([key, m]) => (
          <button
            key={key}
            onClick={() => onPick(key)}
            style={{
              cursor: 'none', border: 'none',
              width: 200, height: 240,
              background: `linear-gradient(160deg, ${m.palette[2]} 0%, ${m.palette[3] || m.palette[2]} 100%)`,
              color: '#fff',
              borderRadius: 18,
              padding: 20,
              display: 'flex', flexDirection: 'column', alignItems: 'flex-start',
              justifyContent: 'space-between',
              boxShadow: '0 18px 40px rgba(0,0,0,0.5)',
              transition: 'transform 0.2s var(--ease), box-shadow 0.2s var(--ease)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = 'translateY(-6px) rotate(-1deg)'
              e.currentTarget.style.boxShadow = `0 26px 50px ${m.accent}55`
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = 'translateY(0) rotate(0)'
              e.currentTarget.style.boxShadow = '0 18px 40px rgba(0,0,0,0.5)'
            }}
          >
            <span style={{ fontSize: '3.2rem', lineHeight: 1 }}>{m.emoji}</span>
            <div style={{ textAlign: 'left' }}>
              <p style={{
                fontFamily: 'var(--font-display)', fontWeight: 800,
                fontSize: '1.8rem', letterSpacing: '-0.02em', lineHeight: 1,
                marginBottom: 6,
              }}>
                {m.label}
              </p>
              <p style={{
                fontFamily: 'var(--font-mono)', fontSize: '0.6rem',
                opacity: 0.85, lineHeight: 1.35,
              }}>
                {m.blurb}
              </p>
            </div>
          </button>
        ))}
      </div>
    </div>
  )
}

function MoodResult({
  moodKey, mood, md, palette,
  onColorChange, onReset, onBack, onCopy, copied, onDownload,
}) {
  const labels = ['background', 'surface', 'accent', 'muted', 'ink']
  return (
    <div style={{
      display: 'grid', gridTemplateColumns: 'minmax(280px, 420px) minmax(320px, 540px)',
      gap: 24, alignItems: 'stretch',
      width: 'min(1020px, 92vw)', maxHeight: '86vh',
      animation: 'fade-in 0.35s var(--ease) both',
    }}>
      {/* Left, controls */}
      <div style={{
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 18, padding: '1.4rem 1.5rem',
        color: '#fff', overflow: 'auto',
        display: 'flex', flexDirection: 'column', gap: 18,
      }}>
        <div>
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: '0.6rem',
            color: mood.accent, letterSpacing: '0.16em', textTransform: 'uppercase',
          }}>
            # {moodKey} mood
          </p>
          <h3 style={{
            fontFamily: 'var(--font-display)', fontWeight: 800,
            fontSize: '1.8rem', letterSpacing: '-0.02em', lineHeight: 1.05,
            marginTop: 4,
          }}>
            {mood.emoji} {mood.label}
          </h3>
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: '0.65rem',
            color: 'rgba(255,255,255,0.65)', marginTop: 8, lineHeight: 1.5,
          }}>
            {mood.blurb}
          </p>
        </div>

        <div>
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            marginBottom: 10,
          }}>
            <p style={{
              fontFamily: 'var(--font-mono)', fontSize: '0.58rem',
              color: 'rgba(255,255,255,0.6)', letterSpacing: '0.14em',
              textTransform: 'uppercase',
            }}>
              palette · click any swatch
            </p>
            <button onClick={onReset} title="Reset palette" style={iconBtn}>
              <RotateCcw size={11} /> reset
            </button>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 8 }}>
            {palette.map((c, i) => (
              <label key={i} style={{
                position: 'relative', display: 'block', cursor: 'none',
                borderRadius: 10, overflow: 'hidden',
                border: '1px solid rgba(255,255,255,0.15)',
                aspectRatio: '1 / 1.2',
              }}>
                <span style={{
                  position: 'absolute', inset: 0,
                  background: c,
                }} />
                <span style={{
                  position: 'absolute', left: 0, right: 0, bottom: 0,
                  padding: '4px 5px',
                  background: 'rgba(0,0,0,0.55)', color: '#fff',
                  fontFamily: 'var(--font-mono)', fontSize: '0.5rem',
                  letterSpacing: '0.06em', textAlign: 'center',
                }}>
                  {c.toUpperCase()}
                </span>
                <input
                  type="color"
                  value={c}
                  onChange={(e) => onColorChange(i, e.target.value)}
                  style={{
                    position: 'absolute', inset: 0, width: '100%', height: '100%',
                    opacity: 0, cursor: 'none', border: 'none',
                  }}
                />
                <span style={{
                  position: 'absolute', top: 4, left: 5,
                  fontFamily: 'var(--font-mono)', fontSize: '0.45rem',
                  color: 'rgba(255,255,255,0.85)',
                  textShadow: '0 1px 2px rgba(0,0,0,0.6)',
                  letterSpacing: '0.1em', textTransform: 'uppercase',
                }}>
                  {labels[i]}
                </span>
              </label>
            ))}
          </div>
        </div>

        <Spec label="Typography">
          {mood.typography.display} · {mood.typography.body} · {mood.typography.mono}
        </Spec>
        <Spec label="Spacing">{mood.spacing}</Spec>
        <Spec label="Radii">{mood.radii}</Spec>
        <Spec label="Voice">{mood.voice}</Spec>

        <div style={{
          display: 'flex', gap: 10, marginTop: 'auto', flexWrap: 'wrap',
        }}>
          <button onClick={onCopy} style={primaryBtn(mood.accent)}>
            {copied ? <><Check size={13} /> copied</> : <><Copy size={13} /> copy .md</>}
          </button>
          <button onClick={onDownload} style={ghostBtn}>
            <Download size={13} /> download
          </button>
          <button onClick={onBack} style={ghostBtn}>
            ← pick again
          </button>
        </div>
      </div>

      {/* Right, md preview */}
      <div style={{
        background: '#0A0A0F',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 18, padding: '1.2rem 1.4rem',
        color: '#E8EBF5', overflow: 'auto',
        fontFamily: 'var(--font-mono)', fontSize: '0.72rem',
        lineHeight: 1.55, whiteSpace: 'pre-wrap',
      }}>
        <p style={{
          fontFamily: 'var(--font-mono)', fontSize: '0.55rem',
          color: 'rgba(255,255,255,0.4)', letterSpacing: '0.18em',
          textTransform: 'uppercase', marginBottom: 12,
        }}>
          design-system-{moodKey}.md
        </p>
        <pre style={{
          margin: 0, fontFamily: 'inherit', fontSize: 'inherit',
          color: 'inherit', background: 'transparent',
          whiteSpace: 'pre-wrap', wordBreak: 'break-word',
        }}>
{md}
        </pre>
      </div>
    </div>
  )
}

function Spec({ label, children }) {
  return (
    <div>
      <p style={{
        fontFamily: 'var(--font-mono)', fontSize: '0.55rem',
        color: 'rgba(255,255,255,0.5)', letterSpacing: '0.14em',
        textTransform: 'uppercase', marginBottom: 4,
      }}>
        {label}
      </p>
      <p style={{ fontSize: '0.78rem', color: '#fff', lineHeight: 1.4 }}>
        {children}
      </p>
    </div>
  )
}

const iconBtn = {
  display: 'inline-flex', alignItems: 'center', gap: 4,
  padding: '4px 8px', cursor: 'none',
  background: 'rgba(255,255,255,0.08)',
  border: '1px solid rgba(255,255,255,0.12)',
  borderRadius: 999, color: '#fff',
  fontFamily: 'var(--font-mono)', fontSize: '0.56rem',
}
const ghostBtn = {
  display: 'inline-flex', alignItems: 'center', gap: 6,
  padding: '0.55rem 0.9rem', cursor: 'none',
  background: 'rgba(255,255,255,0.06)',
  border: '1px solid rgba(255,255,255,0.15)',
  borderRadius: 999, color: '#fff',
  fontFamily: 'var(--font-mono)', fontSize: '0.66rem',
}
const primaryBtn = (accent) => ({
  display: 'inline-flex', alignItems: 'center', gap: 6,
  padding: '0.6rem 1rem', cursor: 'none',
  background: accent, color: '#fff',
  border: 'none', borderRadius: 999,
  fontFamily: 'var(--font-mono)', fontSize: '0.68rem', fontWeight: 700,
  boxShadow: `0 8px 22px ${accent}55`,
})
